site_name: Patch Notifier
site_description: Documentation for the Patch Notifier system on Community Content
docs_dir: docs
extra_css:
  - stylesheets/extra.css
theme:
  palette:
    scheme: slate
    primary: blue
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - toc.integrate
    - navigation.expand
  font:
      text: Lato
      code: JetBrains Mono
  
nav:
  - Documentation:
    - index.md
    - quick-start.md
    - command.md
    - settings.md
    - leaderboard.md
    - notification.md
    - how-does-it-work.md

  - Core Games:
    - https://coregames.com
  - Twitter:
    - https://twitter.com/PIXELDEPTH

  - GitHub:
    - https://pixeldepth.net

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - markdown.extensions.codehilite:
      guess_lang: false
